config/routes.rb
Intervene::Application.routes.draw do
  resources :teachers

  resources :students

  resources :enrollments

  resources :courses

  resources :schools

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  attr_accessible :course_id, :student_id, :teacher_id
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Enrollment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @enrollments }
    end
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
    @enrollment = Enrollment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @enrollment }
    end
  end

  # GET /enrollments/new
  # GET /enrollments/new.json
  def new
    @enrollment = Enrollment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @enrollment }
    end
  end

  # GET /enrollments/1/edit
  def edit
    @enrollment = Enrollment.find(params[:id])
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(params[:enrollment])

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully created.' }
        format.json { render json: @enrollment, status: :created, location: @enrollment }
      else
        format.html { render action: "new" }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /enrollments/1
  # PUT /enrollments/1.json
  def update
    @enrollment = Enrollment.find(params[:id])

    respond_to do |format|
      if @enrollment.update_attributes(params[:enrollment])
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment = Enrollment.find(params[:id])
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<%= form_for(@enrollment) do |f| %>
  <% if @enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% @enrollment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_id %><br />
    <%= f.number_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :teacher_id %><br />
    <%= f.number_field :teacher_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render 'form' %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<h1>Listing enrollments</h1>

<table>
  <tr>
    <th>Course</th>
    <th>Student</th>
    <th>Teacher</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @enrollments.each do |enrollment| %>
  <tr>
    <td><%= enrollment.course_id %></td>
    <td><%= enrollment.student_id %></td>
    <td><%= enrollment.teacher_id %></td>
    <td><%= link_to 'Show', enrollment %></td>
    <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
    <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Enrollment', new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render 'form' %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Course:</b>
  <%= @enrollment.course_id %>
</p>

<p>
  <b>Student:</b>
  <%= @enrollment.student_id %>
</p>

<p>
  <b>Teacher:</b>
  <%= @enrollment.teacher_id %>
</p>


<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>